---
- name: creating user 
  hosts: all
  become: true
  vars_files:
    - user_list.yml
  tasks:
    - name: creating user ID
      vars: 
        password: "{{ lookup('password', './tmp/{{item.name}}-password.txt length=6')}}"
      user:
        name: "{{item.name}}"
        uid: "{{item.uid}}"
        comment: '"{{item.first | capitalize}} {{item.last | capitalize}} {{item.midd | capitalize}}"'
        shell: /bin/bash
        password: "{{ password | password_hash('sha512') }}"
        state: present
        update_password: on_create
      with_items: "{{ users }}"
