---
- hosts: all
  become: true
  vars_files:
    - user_list.yml
  tasks:
    - vars:
        password: "{{ lookup('password', '/tmp/passwordfile length=8 chars=digits') }}"
      user:
        name: "{{item.name}}"
        password: "{{password| password_hash('sha512') }}"
        comment: "{{item.first|capitalize}} {{item.last|capitalize}} {{item.midd|capitalize}}"
        shell: /bin/bash
        update_password: on_create
        state: present
      with_items: "{{users}}"

