---

- name: creating playbook for user create
  hosts: all
  become: true
  vars_files:
    - user_list.yml
  tasks:
    - vars: 
        password: "{{ lookup('password', './{{item.name}}-password.txt length=6') }}"
 
      user:
        name: "{{item.name}}"
        uid: "{{item.uid}}"
        shell: /bin/bash
        password: "{{password | password_hash('sha512')}}"
        state: present
        comment: "{{item.first| capitalize}} {{item.midd| capitalize}} {{item.last| capitalize}}"
        update_password: on_create
      with_items: "{{ users }}"  
         
