---

- name: playbook for user create
  hosts: all
  become: true
  vars_files:
    - user_list.yml
  tasks:
    - name: creating user
      vars: 
        password: "{{lookup('password', './tmp/{{item.name}}-password.txt length=6')}}"
      user:
        name: "{{item.name}}"
        password: "{{password | password_hash('sha512')}}"
        uid: "{{item.uid}}"
        shell: /bin/bash
        comment: "{{item.first|capitalize}} {{item.last| capitalize}} {{item.midd| capitalize}}"
        update_password: on_create
        state: present
      with_items: "{{ user}}"
         
