---
- name: playbook to create user
  hosts: all
  become: true
  vars_files:
    - user_list.yml
  tasks:
    - name: creating user        
      vars:
        password: "{{ lookup('password','./tmp/{{item.name}}-password.txt length=6') }}"
      user:
        name: "{{item.name}}"
        comment: "{{item.first|capitalize}} {{item.last|capitalize}} {{item.midd|capitalize}}"
        password: "{{password| password_hash('sha512')}}"
        shell: /bin/bash
        update_password: on_create
        uid: "{{item.uid}}"
        state: present
      with_items: "{{users}}"
