---
- name: playbook for user ID
  hosts: all
  become: true
  vars_files:
    - user_list.yml
  tasks:
    - vars: 
        password: "{{ lookup('password', './tmp/{{item.name}}-password.txt length=6')}}"
      user:
        name: "{{item.name}}"
        uid: "{{item.uid}}"
        comment: "{{item.first| capitalize}} {{item.midd| capitalize}} {{item.last| capitalize}}"
        state: present
        password: "{{password| password_hash('sha512') }}"
        shell: /bin/bash
        update_password: on_create
      with_items: "{{ users }}" 
